spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 157426.+
    url: jdbc:mysql://localhost:3306/lab
  mvc:
    static-path-pattern: /**
mybatis:
  mapper-locations: mybatis/mapper/*.xml